import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

import { FoundersGrotesk, NeueMontreal } from "@/lib/font/Fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FoundersGrotesk.className}  ${NeueMontreal.variable} `}> {/* ${NeueMontreal.className} ${NeueMontreal.variable}  ${FoundersGrotesk.variable} */}
        {children}
        </body>
    </html>
  );
}
